name: Tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: dschep/install-poetry-action@v1.2

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y --no-install-recommends python3-venv

    - name: Make poetry use Python 3
      run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

    - name: Build package
      run: poetry build

  lint-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install system dependencies
      run: |
        pip3 install flake8 black

    - name: Lint Python
      run: python3 -m flake8 canonicalwebteam setup.py && python3 -m black --line-length 79 --check canonicalwebteam setup.py

  test-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: dschep/install-poetry-action@v1.2

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y --no-install-recommends python3-venv

    - name: Make poetry use Python 3
      run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

    - name: Install package dependencies
      run: poetry install

    - name: Python tests
      run: poetry run pytest
